name: vcharge
description: A new Flutter project.
publish_to: 'none'

version: 3.0.4+17

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.8

  # Navigation & animations
  curved_navigation_bar: ^1.0.6
  lottie: ^3.3.2
  loading_animation_widget: ^1.3.0
  marquee: ^2.3.0

  # Maps & Location
  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  flutter_map_cache: ^1.5.2
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Network & Permissions
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  dio: ^5.9.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_file_store: ^1.2.3

  # Notifications & Storage
  flutter_local_notifications: ^19.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  path_provider: ^2.1.2

  # UI & Icons
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.0
  liquid_progress_indicator_v2: ^0.5.0

  # State management
  get: ^4.6.6
  grouped_list: ^6.0.0

  # Payments
  razorpay_flutter: ^1.3.4

  # QR Scanner
  qr_code_scanner_plus: ^2.0.13

  # Utility packages
  logger: ^2.6.2
  objectbox: ^4.3.1
  objectbox_flutter_libs: ^4.3.1
  package_info_plus: ^8.3.1
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  synchronized: ^3.4.0
  upgrader: ^12.1.0
  url_launcher: ^6.3.2
  vector_graphics: ^1.1.19
  vector_graphics_compiler: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  objectbox_generator: ^4.3.1
  # The test package must match flutter_test’s pinned version
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
